POST http://localhost:9090/register HTTP/1.1
content-Type: application/json

{
  "username": "bundiKladoo",
  "password": "mine24",
  "email": "ladoo@example.com",
  "name": "Radha"
}

###
POST http://localhost:9090/login HTTP/1.1
content-Type: application/json

{
    "email" : "ladoo@example.com",
    "password": "mine24"
}

###
GET http://localhost:9090/get_user_and_profile HTTP/1.1
content-Type: application/json

{
  "token" : "3111c555a38ede9b2b6b3f8d37b58e1822dc19e71015f51f12aa8ab59884b017"
}

###
GET http://localhost:9090/posts HTTP/1.1
###
GET http://localhost:9090/get_user_and_profile HTTP/1.1
content-Type: application/json

{
  "token" : "3111c555a38ede9b2b6b3f8d37b58e1822dc19e71015f51f12aa8ab59884b017"
}

###
POST http://localhost:9090/update_profile_data 
Content-Type: application/json

{
  "token" : "3111c555a38ede9b2b6b3f8d37b58e1822dc19e71015f51f12aa8ab59884b017",
  "bio": "GirishAhari",
  "currentPost": "CTO",
  "postWork": [
    {
      "company":"Microsoft",
      "position":"CTO",
      "years" : "2+"
    }
  ],
  "education": [
    {
      "school":"IIT",
      "degree":"Btech",
      "fieldOfStudy":"2015-2019"
    }
  ]
  
}

###
GET http://localhost:9090/user/get_all_users 

###
POST http://localhost:9090/user_update
content-Type: application/json
{

}

###
GET http://localhost:9090
